# Generated by Django 5.2 on 2025-07-06 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Movie name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration in minutes')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Poster')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Video')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Trailer url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='relations.actor', verbose_name='Actors')),
                ('categories', models.ManyToManyField(related_name='movies', to='relations.category', verbose_name='Categories')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='relations.director', verbose_name='Director')),
                ('release_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relations.releasedate', verbose_name='Release date')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ('-created_at',),
            },
        ),
    ]
