# Generated by Django 5.2 on 2025-06-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Movie name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration in minutes')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Poster')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Trailer url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
