# Generated by Django 5.2 on 2025-06-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_rating_alter_movie_release_date'),
        ('relations', '0003_alter_actor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='relations.actor', verbose_name='Actors'),
        ),
    ]
