# Generated by Django 5.2 on 2025-06-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Movies'},
        ),
    ]
