# Generated by Django 5.2 on 2025-06-26 12:25

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customeruser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[utils.validators.validate_birthday], verbose_name='Birthday'),
        ),
    ]
