# Generated by Django 5.2 on 2025-06-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'Likes'},
        ),
    ]
