# Generated by Django 5.2 on 2025-06-28 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_watchlist'),
        ('movies', '0008_alter_movie_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Watchlists'},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
    ]
