# Generated by Django 5.2 on 2025-07-06 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Actor name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='actor_pictures/', verbose_name='Actor picture')),
            ],
            options={
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Category name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Director name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='director_pictures/', verbose_name='Director picture')),
            ],
            options={
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Invalid date format', regex='^(1888|18[89]\\d|19\\d{2}|20\\d{2}|21\\d{2}|22\\d{2}|23\\d{2}|24\\d{2}|25\\d{2})$')], verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': 'Release dates',
            },
        ),
    ]
