# Generated by Django 5.2 on 2025-06-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Actor name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='actor_pictures/', verbose_name='Actor picture')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Director name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='director_pictures/', verbose_name='Director picture')),
            ],
        ),
    ]
