# Generated by Django 5.2 on 2025-06-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_actor_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'Directors'},
        ),
    ]
